#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  7 20:56:03 2018

@author: jessicahummel
"""

import matplotlib.pyplot as plt
import numpy
import pandas
from plotnine import *

data=pandas.read_csv("data.txt",sep=",",header=0)
data.shape

b=ggplot(data)+theme_classic()+xlab("region")+ylab("observations")

print b+geom_bar(aes(x="factor(region)",y="observations"),stat="summary",fun_y=numpy.mean)

a=ggplot(data,aes(x="region",y="observations"))+theme_classic()+geom_jitter()

print a

#Yes, the bar and scatter plots tell different stories. If you were to look at the bar
#graph, you would see that the means are very similar, yet looking at the scatter plot
#tells you that the spreads are very different. 