#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  7 20:30:51 2018

@author: jessicahummel
"""

#1

import numpy
import pandas
from plotnine import *

sat=pandas.read_csv("sat.txt",sep=",",header=0)
sat.shape
sat.head(5)

a=ggplot(sat,aes(x="GPA",y="SATScore"))+theme_classic()+geom_point()+coord_cartesian()

print a+xlab("GPA")+ylab("SATScore")+stat_smooth(method="lm")

#2

